### ISSUE TITLE
Settle on unified Development Environment

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#4]
Find a set of tools that everyone uses, then update the wiki to reflect the decisions

**Comment by laurent-lao** [comment]
To facilitate Git usage: Sourcetree
If we settle on C#: MonoDevelop (Multiplatform Open-Source C# IDE)

**Comment by tjosepo** [comment]
I didn't know you could use SourceTree with Github. It's a great tool for anyone not comfortable with Git commands. SourceTree get's my approval. That being said, it's really up to preferences as all Git clients act the same.

I just tinkered a bit with C# and .NET, and it seems like a great option for backend!
I do not know about MonoDevelop. Personally, I am fine with just using VS Code and using a CLI for running .NET. That being said, it is possible to have projects be compatible on both VS Code and Monodevelop. If I am the only one wanting to use VS Code, I will yield.

**Comment by laurent-lao** [comment]
Created https://github.com/CamilBouzidi/-REDACTED-a-SOEN-341-Repo/wiki/Git-Help for getting started with git on bash

**Comment by laurent-lao** [comment]
So I researched a bit more and if we are using .Net Core, then either JetBrains' Rider (free for students) or VSCode would be good.

Advantage with Rider is that we can develop a uniform dev environment and enforce coding style. VSCode is good and lightweight, but without such advantages. Plus, refactoring is limited.

**Comment by CamilBouzidi** [comment]
I have been looking into it as well, and it seems like .NET seems like a great candidate, and so does .NET Core.

My only issue with .NET is that it is a Windows-only framework. Depending on where we host our website, this could be an issue. We could rent Windows servers or create a local server on one of our own Windows PCs. Server-based web apps, from my understanding, are much easier to handle in .NET than .NET Core.

.NET Core, on the other hand, is cross-platform, which is great if we want to rent cloud storage on AWS or GCloud (I know for a fact that they both support Linux). It is a harder learning curve, though. 

What do you guys think? Here is a nice breakdown from September 2019: https://dzone.com/articles/net-framework-vs-net-core

**Comment by tjosepo** [comment]
@CamilBouzidi I didn't even notice that there were two distinct versions of .NET. I don't know if anyone in our group working on a Mac. I think **I would personally favour .NET Core** due to it being slightly more popular and apparently it being much easier to deploy.

@laurentlaurent In regards to enforcing coding styles, many add-ons and programs can be used with VS Code to ensure a consistent coding style. The teacher posted on Moodle a list of static analysis tools (i.e. style enforcers) that can be used with any languages.  It's just a pain because we have to manually add those programs to our build process, whereas Rider does it automatically.

**I think Rider would allow be a good choice**. It would allow us to code more efficiently, and I'm also down to try new things and learn how to use new IDEs.

**Comment by jmezaber** [comment]
@tommy-josepovic I am working on Mac, so of course, using .NET Core would be best.

**Comment by CamilBouzidi** [comment]
Hi all, 

It seems that Rider only has a 30-day trial version. I do not recommend using it if that is the case, since it is unlikely that we will have finished the project in 30 days.

**Comment by laurent-lao** [comment]
@tommy-josepovic I too am developing on Mac 🙌

**Comment by CamilBouzidi** [comment]
As an update following the meeting minutes, I think we could the [SettingsSync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) in order to share our environment (extensions and settings) across PCs. This would make VSCode a very good option!

My only "problem" with VSCode is that it does not natively allow the creation of a .NET CORE solution. I will look into extensions that allow us to do so.

**Comment by laurent-lao** [comment]
@CamilBouzidi might be just simpler to go with Rider in that case (sorry, I am a huge JetBrains convert since IntelliJ)

**Comment by laurent-lao** [comment]
I made two ASP.NET Core branches generated by Rider:
One is for Angular, the other one is for React. Check them out and see if you can load them properly through Rider.

**Comment by CamilBouzidi** [comment]
Hello!

There is a difference between .NET, ASP.NET, .NET CORE and ASP.NET CORE. Just thought I would mention it

**Comment by laurent-lao** [comment]
@CamilBouzidi From what I understand, ASP.NET Core is compatible with the .NET Core stuff, but provides a framework to build a web app. I'll defer to your expertise in that area

**Comment by CamilBouzidi** [comment]
If we use Angular, ASP.NET CORE is redundant in my opinion. We can talk about it more in detail later, though! I have only use .NET CORE (no ASP), so I am far from an expert.
